[package]
name = "riftnet-connection"
version = "0.1.0"
edition = "2021"

[dependencies]
riftnet-protocol = { path = "../protocol" }
riftnet-encryption = { path = "../encryption" }
riftnet-compression = { path = "../compression" }

zerocopy = { version = "0.7", features = ["derive"] }
tracing = "0.1.44"